
package tn.mycompany.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.mycompany.tn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.ConvertResponse")
    @Action(input = "http://ws.mycompany.tn/BanqueService/convertRequest", output = "http://ws.mycompany.tn/BanqueService/convertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<tn.mycompany.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.CompteListResponse")
    @Action(input = "http://ws.mycompany.tn/BanqueService/compteListRequest", output = "http://ws.mycompany.tn/BanqueService/compteListResponse")
    public List<Compte> compteList();

    /**
     * 
     * @param code
     * @return
     *     returns tn.mycompany.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.mycompany.tn/", className = "tn.mycompany.proxy.GetCompteResponse")
    @Action(input = "http://ws.mycompany.tn/BanqueService/getCompteRequest", output = "http://ws.mycompany.tn/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
